#!/usr/bin/env node
/**
 * audit.mjs — ground truth for the Token course.
 *
 * WHY THIS EXISTS
 * ---------------
 * Twice, prose in CLAUDE.md and HANDOFF.md asserted things nobody could check
 * ("Modules 1 and 2 complete" when 2 lessons were done; a search index that had
 * silently decayed to 65 of 95 entries). Both survived for months because they
 * were claims, not measurements.
 *
 * So: anything a script can compute lives ONLY in PROGRESS.md, and PROGRESS.md
 * is generated by this file. If a document ever disagrees with this script,
 * the script wins.
 *
 *   node scripts/audit.mjs          # print report, write PROGRESS.md
 *   node scripts/audit.mjs --check  # print report, exit 1 on errors (CI)
 *   node scripts/audit.mjs --quiet  # write PROGRESS.md, print only the summary
 *
 * Run from the course root (the folder containing modules/ and assets/).
 */

import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";
import { scanPreBlocks } from "./check-pre-blocks.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const args = new Set(process.argv.slice(2));
const CHECK = args.has("--check");
const QUIET = args.has("--quiet");

/** Token code alphabet — see CLAUDE.md § Token code format. 0/O/1/I/L excluded. */
const TOKEN_ALPHABET = "23456789ABCDEFGHJKMNPQRSTUVWXYZ";

/** A lesson counts as "deepened" once it carries all three spine sections. */
const DEEPENED_MARKERS = [/why this way/i, /when this breaks/i, /what this costs/i];

const errors = [];
const warnings = [];
const err = (m) => errors.push(m);
const warn = (m) => warnings.push(m);

// ---------------------------------------------------------------- helpers

const read = (p) => fs.readFileSync(p, "utf8");
const exists = (p) => fs.existsSync(p);

function walk(dir, out = []) {
  if (!exists(dir)) return out;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, out);
    else out.push(p);
  }
  return out;
}

/** Repo-relative, forward-slashed — stable across Windows and POSIX. */
const rel = (p) => path.relative(ROOT, p).split(path.sep).join("/");

/** Legacy = the 45 pre-pivot WhatsApp-era lessons in modules/03- .. 09-. */
const isLegacy = (p) => /modules\/0[3-9]-/.test(rel(p));

const decode = (s) =>
  s
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&amp;/g, "&");

/** Body text with all <script> blocks removed — what the student actually reads. */
function proseOf(html) {
  const body = html.replace(/<script[\s\S]*?<\/script>/g, " ");
  const text = body
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  return { body, words: text ? text.split(" ").length : 0 };
}

/** Run a lesson's inline scripts in a sandbox, capturing createQuiz() payloads. */
function extractQuizzes(html, file) {
  const out = [];
  const re = /<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g;
  let m;
  while ((m = re.exec(html))) {
    const src = m[1];
    // Every inline block must parse — an unescaped </script> silently kills it.
    try {
      new vm.Script(src);
    } catch (e) {
      err(`${file}: inline <script> does not parse — ${e.message.slice(0, 80)}`);
      continue;
    }
    if (!/createQuiz\s*\(/.test(src)) continue;
    const permissive = new Proxy(function () {}, {
      get: () => permissive,
      apply: () => permissive,
      set: () => true,
      has: () => true,
      construct: () => permissive,
    });
    const ctx = {
      createQuiz: (id, qs) => Array.isArray(qs) && out.push(...qs),
      createPlayground() {},
      createSolution() {},
      document: permissive,
      window: permissive,
      localStorage: permissive,
      console: { log() {}, warn() {}, error() {} },
      setTimeout() {},
      addEventListener() {},
    };
    ctx.globalThis = ctx;
    try {
      vm.createContext(ctx);
      new vm.Script(src).runInContext(ctx, { timeout: 5000 });
    } catch (e) {
      err(`${file}: inline <script> threw — ${e.message.slice(0, 80)}`);
    }
  }
  return out;
}

/**
 * fill-blank renders ONE text box and grades by exact string compare, so a
 * question with several blanks only works when the same word fills every one.
 * Most do — `import { readFile } … await readFile(…)` is fine.
 *
 * This used to warn on the blank count alone. That fired 24 times, 21 of them
 * correct, and a warning that is 87% noise is a warning nobody reads: three
 * genuinely unanswerable questions sat behind it until 2026-08-17. The count
 * carried no signal, so it is gone. What replaces it are three checks that are
 * exact about the ways one answer provably cannot fill every blank.
 *
 * Still not caught, and no static check can: blanks far apart that happen to
 * want different words. `new ___()` … `controller.___()` needed
 * `AbortController` then `abort`, and only reading it tells you.
 */
function validateBlanks(q, at) {
  const code = String(q.code);
  const answer = String(q.answer || "");

  // 1. An answer spliced across blanks — `max(128` for `.___(___, …)`. Whatever
  //    the student types, it cannot be this, because this is not a thing.
  const pairs = { ")": "(", "]": "[", "}": "{" };
  const stack = [];
  let balanced = true;
  for (const ch of answer) {
    if ("([{".includes(ch)) stack.push(ch);
    else if (ch in pairs && stack.pop() !== pairs[ch]) balanced = false;
  }
  if (!balanced || stack.length)
    err(`${at}: answer ${JSON.stringify(answer)} has unbalanced brackets — spliced across blanks?`);

  // Three underscores, not two: `__dirname` and `__DEV__` are ordinary code and
  // were being counted as blanks. That is the same mistake in the checker that
  // `___dirname` was in the lesson — the first version of this check reported
  // a8/0001 as broken on the strength of it.
  const blanks = [...code.matchAll(/_{3,}/g)];
  if (blanks.length < 2) return;

  // 2. Blanks separated by punctuation only — `item.___.___()`, `.___(___,`.
  //    One string cannot be both halves of a member chain or both a call and
  //    its own argument.
  for (let k = 1; k < blanks.length; k++) {
    const gap = code.slice(blanks[k - 1].index + blanks[k - 1][0].length, blanks[k].index);
    if (gap && /^[.,()[\]{}]+$/.test(gap))
      err(`${at}: blanks separated only by "${gap}" — they need different answers`);
  }

  // 3. One blank a property name, another not — `new ___()` vs `obj.___()`.
  //    The answer would have to play two incompatible roles.
  const member = blanks.map((b) => code[b.index - 1] === ".");
  if (member.some(Boolean) && !member.every(Boolean))
    err(`${at}: some blanks are property positions and some are not — one answer cannot fill both`);
}

function validateQuestion(q, file, i) {
  const t = q.type || "multiple-choice";
  const at = `${file} q${i}`;
  if (!q.explanation || !String(q.explanation).trim())
    err(`${at}: missing explanation`);

  if (t === "multiple-choice" || t === "spot-the-bug") {
    if (!Array.isArray(q.options)) return err(`${at}: no options array`);
    if (typeof q.correct !== "number") return err(`${at}: correct is not a number`);
    if (q.correct < 0 || q.correct >= q.options.length)
      err(`${at}: correct=${q.correct} out of range (${q.options.length} options)`);
    /* quiz.js shuffles options at render (optionDisplayOrder), so an option
       naming other options — "Both A and B", "all of the above" — is broken
       wherever it sits, not merely when it is not last. The old check warned
       only on position, so six of the seven "Both A and B" options in the
       course passed silently while being just as broken; and it matched a bare
       "Neither", flagging "Neither — use a WebView instead", which references
       nothing. Name the content, not the letters. */
    q.options.forEach((o, j) => {
      const text = String(o).trim();
      if (/\b(both|either|neither)\s+a\s+and\s+b\b/i.test(text) || /\b(all|none|both|neither) of the above\b/i.test(text))
        err(`${at}: option ${j} names other options ("${text.slice(0, 40)}") — options are shuffled at render`);
    });
  } else if (t === "which-breaks") {
    if (!Array.isArray(q.variants)) return err(`${at}: no variants array`);
    if (typeof q.correct !== "number" || q.correct < 0 || q.correct >= q.variants.length)
      err(`${at}: correct=${q.correct} out of range (${q.variants.length} variants)`);
    // A "which is correct?" question tagged which-breaks renders under the
    // fixed prompt "Which of these will fail?" — the key then rewards the
    // RIGHT option while the screen asks for the failing one.
    const text = String(q.question || "");
    if (/\b(correct|right|best|proper)\b/i.test(text) && !/\b(break|fail|wrong|error|reject|NOT )/i.test(text))
      err(`${at}: which-breaks phrased as "which is correct?" — semantics inverted`);
  } else if (t === "order-steps") {
    if (!Array.isArray(q.steps) || !Array.isArray(q.correctOrder))
      return err(`${at}: missing steps/correctOrder`);
    if (q.steps.length !== q.correctOrder.length)
      err(`${at}: steps=${q.steps.length} but correctOrder=${q.correctOrder.length}`);
    const sorted = [...q.correctOrder].sort((a, b) => a - b).join(",");
    if (sorted !== q.steps.map((_, k) => k).join(","))
      err(`${at}: correctOrder is not a permutation of 0..${q.steps.length - 1}`);
  } else if (t === "fill-blank") {
    if (!q.answer || !String(q.answer).trim()) err(`${at}: missing answer`);
    if (!q.code || !/_{3,}/.test(q.code)) err(`${at}: code has no ___ blank`);
    else validateBlanks(q, at);
  } else if (t === "predict-output") {
    if (q.answer === undefined || q.answer === null) err(`${at}: missing answer`);
    if (!q.code) err(`${at}: missing code`);
  } else {
    warn(`${at}: unknown question type "${t}"`);
  }
  return undefined;
}

/* Mirrors explanationNamesAPosition() in assets/quiz.js. */
const namesAPosition = (text) =>
  /\b(?:option|answer|choice)\s+[A-D]\b/i.test(text) ||
  /\bthe\s+(?:first|second|third|fourth|last)\s+(?:option|answer|choice|one)\b/i.test(text);

const fixedOrder = { total: 0, positions: {} };

// ---------------------------------------------------------------- scan

const lessonFiles = walk(path.join(ROOT, "modules"))
  .filter((p) => p.endsWith(".html") && /\/0\d{3}-/.test(rel(p)))
  .sort();

const verificationLog = exists(path.join(ROOT, "scripts", "verification-log.json"))
  ? JSON.parse(read(path.join(ROOT, "scripts", "verification-log.json")))
  : {};

const lessons = [];
const positions = {};
const typeCounts = {};

for (const file of lessonFiles) {
  const html = read(file);
  const id = rel(file);
  const { body, words } = proseOf(html);
  const questions = isLegacy(file) ? [] : extractQuizzes(html, id);

  if (!isLegacy(file)) {
    questions.forEach((q, i) => {
      validateQuestion(q, id, i);
      const t = q.type || "multiple-choice";
      typeCounts[t] = (typeCounts[t] || 0) + 1;
      if (["multiple-choice", "spot-the-bug", "which-breaks"].includes(t) && typeof q.correct === "number") {
        positions[q.correct] = (positions[q.correct] || 0) + 1;
        /* quiz.js shuffles options at render, so authored position is invisible
           to the student — EXCEPT where it refuses to shuffle: a question whose
           explanation names an option by position renders as authored, because
           shuffling would make the explanation contradict the screen. Those are
           the only ones where clustering is still a scoring exploit, so they get
           counted separately. Predicate copied from assets/quiz.js; if it
           changes there, change it here. */
        if (namesAPosition(q.explanation || "")) {
          fixedOrder.total++;
          fixedOrder.positions[q.correct] = (fixedOrder.positions[q.correct] || 0) + 1;
        }
      }
    });
  }

  lessons.push({
    id,
    module: id.split("/")[1],
    legacy: isLegacy(file),
    words,
    pre: (body.match(/<pre/g) || []).length,
    playgrounds: (html.match(/createPlayground\(/g) || []).length,
    exercises: (html.match(/createSolution\(/g) || []).length,
    questions: questions.length,
    deepened: DEEPENED_MARKERS.every((r) => r.test(body)),
    verified: verificationLog[id]?.status ?? "unverified",
  });
}

// -------------------------------------------------- cross-lesson: schema

const created = new Map();
const queried = new Map();

/**
 * Match SQL *grammar*, not whole blocks. Two failure modes to avoid:
 *   - Scanning every <pre> for bare FROM/JOIN pulls in English from JS comments
 *     and invents dozens of tables.
 *   - Scanning only blocks that "look like SQL" misses SQL inside JS string
 *     literals — which is where most of the real queries live.
 * Requiring a SQL continuation token after the table name handles both.
 */
const REFS = [
  /\bINSERT\s+INTO\s+([a-z_]{3,})\s*\(/gi,
  /\bUPDATE\s+([a-z_]{3,})\s+SET\b/gi,
  /\bDELETE\s+FROM\s+([a-z_]{3,})\b/gi,
  // A bare /FROM (\w+)/ matches English ("returned from the screen"), so the
  // statement must actually open with SELECT.
  /\bSELECT\b[\s\S]{0,400}?\bFROM\s+([a-z_]{3,})\b/gi,
  /\bJOIN\s+([a-z_]{3,})(?:\s+(?:AS\s+)?[a-z_]{1,3})?\s+ON\b/gi,
];
const SQL_KEYWORDS = new Set(["select", "values", "where", "only", "dual", "set", "and", "not", "null"]);

for (const file of lessonFiles) {
  if (isLegacy(file)) continue; // pre-pivot Firebase lessons share no schema
  const html = read(file).replace(/<script[\s\S]*?<\/script>/g, "");
  const code = [...html.matchAll(/<pre[^>]*>([\s\S]*?)<\/pre>/g)]
    .map((m) => decode(m[1].replace(/<[^>]+>/g, "")))
    .join("\n");
  for (const m of code.matchAll(/CREATE TABLE(?:\s+IF NOT EXISTS)?\s+([a-z_]+)/gi))
    if (!created.has(m[1].toLowerCase())) created.set(m[1].toLowerCase(), rel(file));
  for (const re of REFS)
    for (const m of code.matchAll(re)) {
      const t = m[1].toLowerCase();
      if (SQL_KEYWORDS.has(t)) continue;
      if (!queried.has(t)) queried.set(t, new Set());
      queried.get(t).add(rel(file));
    }
}
const orphanTables = [...queried.entries()].filter(([t]) => !created.has(t));
for (const [t, files] of orphanTables)
  err(`schema: table "${t}" is queried in ${[...files].length} lesson(s) but never created`);

// -------------------------------------------------- cross-lesson: links

let brokenLinks = 0;
for (const file of walk(path.join(ROOT, "modules")).filter((p) => p.endsWith(".html"))) {
  const html = read(file);
  for (const m of html.matchAll(/href="(\.[^"#?]*\.html)"/g)) {
    const target = path.normalize(path.join(path.dirname(file), m[1]));
    if (exists(target)) continue;
    // Legacy modules are superseded and linked from nothing — a dead link there
    // is a curiosity, not a defect. Failing on it would train people to ignore
    // the audit, which is the one thing it cannot survive.
    if (isLegacy(file)) warn(`link (legacy): ${rel(file)} -> ${m[1]}`);
    else {
      err(`link: ${rel(file)} -> ${m[1]} (missing)`);
      brokenLinks++;
    }
  }
}

// -------------------------------------------------- search index

let indexStatus = "absent";
const indexPath = path.join(ROOT, "assets", "search-index.json");
if (exists(indexPath)) {
  const idx = JSON.parse(read(indexPath));
  const dead = idx.filter((e) => !exists(path.join(ROOT, e.path.replace(/^\.\//, ""))));
  const indexed = new Set(idx.map((e) => e.path.replace(/^\.\//, "")));
  const missing = lessons.filter((l) => !l.legacy && !indexed.has(l.id));
  dead.forEach((d) => err(`search-index: dead path ${d.path}`));
  missing.forEach((m) => err(`search-index: lesson not indexed — ${m.id}`));
  indexStatus = `${idx.length} entries, ${dead.length} dead, ${missing.length} unindexed`;
}

// -------------------------------------------------- display <pre> blocks

/* verify-lesson.mjs only runs what a lesson EXECUTES. A plain <pre><code>
   block is display-only, so a broken one passes every check and still fails in
   the student's editor when they copy it. 02/0014 carried a shell-mangle
   fragment (`timy!',`) for a fortnight while marked `verified`.

   An error, not a warning: the block is wrong, there is nothing to weigh up,
   and it is the paste that a lesson exists to hand over. See
   scripts/test-check-pre-blocks.mjs for what it does and does not catch. */
const preScan = scanPreBlocks(path.join(ROOT, "modules"));
preScan.findings.forEach((f) =>
  err(`display block: unterminated ${f.quote} string — ${f.file}:${f.line}`));

// -------------------------------------------------- token alphabet

const badTokens = new Map();
/* This check protects *teaching* material — a code a student might copy. The
   log and plan files are neither, and every code in them is either a historical
   reference or a description of a fix that has already landed. Scanning them
   punished the work twice over:

     - PROGRESS.md is this script's own output and prints every offending code
       inside its warnings, so a code fixed everywhere a student could see it
       stayed reported forever and the list could never reach zero;
     - SESSION.md warned about WAVE-1MN4 and XPRT-4KL9 purely because the entry
       recording their removal names them. Writing an honest session note made
       the audit noisier, which is precisely backwards.

   A list that cannot reach zero stops being read — the same way 24 blank-count
   warnings hid three broken questions until 2026-08-17. CLAUDE.md is still
   scanned, deliberately: it carries the canonical example a lesson copies, and
   a wrong code there is how MERC-8GH2-LP4X reached 36 files. */
const NARRATIVE = /^(PROGRESS|SESSION|HANDOFF|TOKEN-TRACK)\.md$|^docs\//;
const tokenScan = [
  ...lessonFiles,
  ...walk(ROOT).filter(
    (p) => p.endsWith(".md") && !rel(p).startsWith("node_modules") && !NARRATIVE.test(rel(p))
  ),
];
for (const file of tokenScan) {
  const text = read(file);
  /* A lesson whose subject IS invalid codes needs a supply of them. 02/0004
     teaches the redemption field, so every excluded character appears there on
     purpose, as the thing being rejected. Marking the file opts it out — the
     same bargain as `audit-allow-alphabet` above, and taken for the same
     reason: six deliberate warnings train people to ignore the list, which is
     how the real ones hid. The alphabet check, which is an error and the
     dangerous one, still applies to these files. */
  /* Honoured in lesson files only. `CLAUDE.md` documents this marker, and a
     plain substring test let that prose opt the whole file out — including the
     canonical-code story it exists to protect. A marker must be claimable only
     by the content it guards. */
  if (file.endsWith(".html") && text.includes("audit-allow-token-fixtures")) continue;
  /* Line-level opt-out, for a document that must keep being scanned but has one
     legitimate reason to name a bad code. CLAUDE.md explains that the canonical
     example used to be MERC-8GH2-LP4X and that the L made it unissuable — the
     warning was firing on the paragraph documenting the very bug the check
     exists to prevent, which is the SESSION.md/HANDOFF.md mistake again, one
     scope smaller. A whole-file marker is wrong here for the reason given
     below: CLAUDE.md carries the canonical code a lesson copies. */
  const lineOf = (index) => text.slice(0, index).split("\n").length - 1;
  const textLines = text.split("\n");
  for (const m of text.matchAll(/\b([A-Z0-9]{4}-[A-Z0-9]{4}(?:-[A-Z0-9]{4})?)\b/g)) {
    if ((textLines[lineOf(m.index)] || "").includes("audit-allow-token-here")) continue;
    const bad = [...m[1].replace(/-/g, "")].filter((c) => !TOKEN_ALPHABET.includes(c));
    if (!bad.length) continue;
    /* "0001-0004" is a lesson range, not a token. Every real example code in
       this course carries a letter label in the first group. */
    if (/^\d{4}-/.test(m[1])) continue;
    if (/^(TEST|NOPE|OLD1|NEW1|ABCD|IJKL|AAAA|EFGH|ZZZZ|DTLS|HMAC|XXXX)/.test(m[1])) continue; // fixtures
    if (!badTokens.has(m[1])) badTokens.set(m[1], new Set());
    badTokens.get(m[1]).add(rel(file));
  }
}
for (const [t, files] of badTokens)
  warn(`token: "${t}" uses characters excluded from the alphabet (${[...files].length} file(s))`);

/* The check above catches a bad *code*. It cannot catch a bad *alphabet* — and
   an alphabet defect is worse, because it generates an unlimited supply of bad
   codes rather than one wrong example. Three lessons taught
   `ABCDEFGHJKLMNPQRSTUVWXYZ23456789` as "no 0/O/1/I/L" while including L, so
   the server generated codes the client's validator rejects.

   Anything that looks like a code alphabet — a long unbroken run of A-Z0-9 in
   a string literal — must be the canonical one. This is an ERROR, not a
   warning: the alphabet is the one constraint in CLAUDE.md that cannot be
   fixed retroactively for codes already issued. */
const alphabetOffenders = new Map();
for (const file of lessonFiles) {
  if (isLegacy(file)) continue;
  const html = read(file);
  /* A lesson that shows a wrong alphabet on purpose — to teach why L is not in
     it — is doing the right thing. Marking the file opts it out, so a genuine
     counter-example never trains anyone to ignore this check. */
  if (html.includes("audit-allow-alphabet")) continue;
  for (const m of html.matchAll(/['"`]([A-Z0-9]{20,})['"`]/g)) {
    const literal = m[1];
    if (literal === TOKEN_ALPHABET) continue;
    /* A token alphabet contains digits. Without this, the plain English
       A-Z — pasted into a maxLength question in 02/0004 — reads as one. */
    if (!/[0-9]/.test(literal)) continue;
    // Only judge strings that are plausibly an alphabet: mostly the canonical
    // characters, in ascending runs. A base64 blob or a hash is neither.
    const shared = [...new Set(literal)].filter((c) => TOKEN_ALPHABET.includes(c)).length;
    if (shared < 20) continue;
    const excluded = [...new Set(literal)].filter((c) => "0O1IL".includes(c));
    if (!alphabetOffenders.has(literal)) alphabetOffenders.set(literal, { files: new Set(), excluded });
    alphabetOffenders.get(literal).files.add(rel(file));
  }
}
for (const [literal, { files, excluded }] of alphabetOffenders) {
  const why = excluded.length
    ? `includes ${excluded.join(", ")}, which the alphabet excludes`
    : `is ${literal.length} characters, not ${TOKEN_ALPHABET.length}`;
  err(`alphabet: "${literal}" ${why} — ${[...files].join(", ")}`);
}

// -------------------------------------------------- known, blocked issues

/* Split the errors into "new" and "already known and gated". See
   scripts/known-issues.json for why this exists — in short, the audit had been
   exiting FAIL on the same three orphan tables every run, and a build that is
   always red is read as often as a warning list that is mostly noise.

   Kept honest from both ends: an unmatched error still fails, AND an
   acknowledgement matching nothing fails as stale. Without that second rule
   this file becomes where errors go to be forgotten. */
const knownPath = path.join(ROOT, "scripts", "known-issues.json");
const known = exists(knownPath) ? JSON.parse(read(knownPath)).acknowledged ?? [] : [];

const acknowledged = [];
const liveErrors = [];
for (const e of errors) {
  const hit = known.find((k) => e.includes(k.match));
  (hit ? acknowledged : liveErrors).push(hit ? { text: e, ...hit } : e);
}

const stale = known.filter((k) => !errors.some((e) => e.includes(k.match)));
stale.forEach((k) =>
  liveErrors.push(
    `known-issues: "${k.match}" no longer matches any error — the problem is ` +
    `fixed or the check changed; delete the entry`));

// ---------------------------------------------------------------- report

const track = lessons.filter((l) => !l.legacy);
const legacy = lessons.filter((l) => l.legacy);
const totalQ = track.reduce((a, l) => a + l.questions, 0);
const keyed = Object.values(positions).reduce((a, b) => a + b, 0);
const avg = (xs) => (xs.length ? Math.round(xs.reduce((a, b) => a + b, 0) / xs.length) : 0);

const byModule = new Map();
for (const l of track) {
  if (!byModule.has(l.module)) byModule.set(l.module, []);
  byModule.get(l.module).push(l);
}

const pct = (n) => (keyed ? ((100 * n) / keyed).toFixed(1) + "%" : "—");
const stamp = new Date().toISOString().slice(0, 10);

let md = `# PROGRESS

<!-- GENERATED BY scripts/audit.mjs — DO NOT EDIT BY HAND.
     Regenerate with: node scripts/audit.mjs
     Hand-written session state lives in SESSION.md, never here. -->

Generated ${stamp} from the files on disk. Where any other document disagrees
with this one, this one is right — everything below is measured, not asserted.

## Summary

| Metric | Value |
|---|---|
| Token-track lessons | ${track.length} |
| Legacy lessons (pre-pivot, excluded) | ${legacy.length} |
| Quiz questions (track) | ${totalQ} |
| Avg teaching prose per track lesson | ${avg(track.map((l) => l.words))} words |
| Lessons with a playground | ${track.filter((l) => l.playgrounds > 0).length} / ${track.length} |
| Lessons with an exercise | ${track.filter((l) => l.exercises > 0).length} / ${track.length} |
| **Deepened** (all 3 spine sections) | ${track.filter((l) => l.deepened).length} / ${track.length} |
| **Verified** (code executed) | ${track.filter((l) => l.verified === "verified").length} / ${track.length} |
| Ran clean but had nothing to run | ${track.filter((l) => l.verified === "nothing-to-verify").length} / ${track.length} |
| Errors | ${liveErrors.length} |
| Known and blocked | ${acknowledged.length} |
| Warnings | ${warnings.length} |

Student-completed lessons are **not** tracked here — that comes from the student
or from \`progress.js\` localStorage, and is never inferred from the files.

## Answer-position distribution — **authored order, not what the student sees**

${keyed} keyed questions (multiple-choice, spot-the-bug, which-breaks).

> **This clustering is expected and already handled. Do not "fix" it again.**
> \`quiz.js\` shuffles options at render time (\`optionDisplayOrder\`), so the
> displayed distribution is roughly even — measured at 26.9 / 28.5 / 26.9 / 17.6
> across all ${keyed} questions, versus the authored figures below. Index 3 sits
> lower only because many questions have three options.
>
> The numbers here read \`correct\` straight from the lesson data, which is
> deliberately unchanged: rewriting 1,284 keys risks breaking them, while a
> renderer change cannot. What this table is good for is catching a *new* batch
> of questions authored with the same habit.
>
> **The one place authored order still reaches the student:** \`quiz.js\` refuses
> to shuffle a question whose explanation names an option by position ("Option A
> creates a label statement"), because shuffling would make the explanation
> contradict the screen. Those render exactly as authored, so clustering in them
> is a real if small scoring edge — **${fixedOrder.total} question(s)**, distributed
> ${[0, 1, 2, 3].map((i) => `${i}=${fixedOrder.total ? ((100 * (fixedOrder.positions[i] || 0)) / fixedOrder.total).toFixed(1) + "%" : "—"}`).join("  ")}.
> Rewriting those explanations to stop naming positions is the fix, and it frees
> them to shuffle like the rest. That is deepening-pass work.

| Position | Count | Share |
|---|---|---|
${[0, 1, 2, 3].map((i) => `| index ${i} | ${positions[i] || 0} | ${pct(positions[i] || 0)} |`).join("\n")}

## Question types

| Type | Count |
|---|---|
${Object.entries(typeCounts).sort((a, b) => b[1] - a[1]).map(([t, n]) => `| ${t} | ${n} |`).join("\n")}

## Modules

| Module | Lessons | Avg prose | Playgrounds | Exercises | Questions | Deepened | Verified |
|---|---|---|---|---|---|---|---|
${[...byModule.entries()]
  .map(([m, ls]) => {
    const d = ls.filter((l) => l.deepened).length;
    const v = ls.filter((l) => l.verified === "verified").length;
    return `| ${m} | ${ls.length} | ${avg(ls.map((l) => l.words))} | ${ls.reduce((a, l) => a + l.playgrounds, 0)} | ${ls.reduce((a, l) => a + l.exercises, 0)} | ${ls.reduce((a, l) => a + l.questions, 0)} | ${d}/${ls.length} | ${v}/${ls.length} |`;
  })
  .join("\n")}

## Integrity checks

| Check | Result |
|---|---|
| Inline \`<script>\` blocks parse | ${errors.some((e) => /does not parse|threw/.test(e)) ? "FAIL" : "ok"} |
| Quiz structure valid | ${errors.some((e) => /\bq\d+:/.test(e)) ? "FAIL" : "ok"} |
| Tables queried but never created | ${orphanTables.length === 0 ? "ok" : orphanTables.map(([t]) => t).join(", ")} |
| Broken relative links | ${brokenLinks === 0 ? "ok" : brokenLinks} |
| search-index.json | ${indexStatus} |
| Example tokens valid under alphabet | ${badTokens.size === 0 ? "ok" : badTokens.size + " invalid"} |

${liveErrors.length ? `## Errors (${liveErrors.length})\n\n${liveErrors.map((e) => `- ${e}`).join("\n")}\n` : "## Errors\n\nNone.\n"}
${acknowledged.length ? `## Known and blocked (${acknowledged.length})

Real problems with a named gate, acknowledged in \`scripts/known-issues.json\`
so they do not hold the audit red. They are **not** resolved.

${acknowledged.map((a) => `- ${a.text}\n  - **why:** ${a.why}\n  - **gate:** ${a.gate} _(since ${a.since})_`).join("\n")}
` : ""}
${warnings.length ? `## Warnings (${warnings.length})\n\n${warnings.slice(0, 40).map((w) => `- ${w}`).join("\n")}${warnings.length > 40 ? `\n- …and ${warnings.length - 40} more` : ""}\n` : ""}
## Per-lesson detail

| Lesson | Prose | Pre | Play | Exer | Q | Deepened | Verified |
|---|---|---|---|---|---|---|---|
${track.map((l) => `| ${l.id.replace("modules/", "")} | ${l.words} | ${l.pre} | ${l.playgrounds} | ${l.exercises} | ${l.questions} | ${l.deepened ? "yes" : "—"} | ${l.verified === "verified" ? "yes" : l.verified === "unverifiable" ? "n/a" : l.verified === "nothing-to-verify" ? "none" : "—"} |`).join("\n")}
`;

fs.writeFileSync(path.join(ROOT, "PROGRESS.md"), md);

// ---------------------------------------------------------------- stdout

if (!QUIET) {
  console.log(`\nToken-track lessons : ${track.length}   (legacy excluded: ${legacy.length})`);
  console.log(`Quiz questions      : ${totalQ}`);
  console.log(`Avg prose / lesson  : ${avg(track.map((l) => l.words))} words`);
  console.log(`Deepened            : ${track.filter((l) => l.deepened).length}/${track.length}`);
  console.log(`Verified            : ${track.filter((l) => l.verified === "verified").length}/${track.length}`);
  console.log(`Answer positions    : ${[0, 1, 2, 3].map((i) => `${i}=${pct(positions[i] || 0)}`).join("  ")}  (authored; shuffled at render)`);
  console.log(`  render-as-authored: ${fixedOrder.total} question(s) — ` +
    `${[0, 1, 2, 3].map((i) => `${i}=${fixedOrder.total ? ((100 * (fixedOrder.positions[i] || 0)) / fixedOrder.total).toFixed(1) + "%" : "—"}`).join("  ")}`);
  if (liveErrors.length) {
    console.log(`\n${liveErrors.length} ERROR(S):`);
    liveErrors.slice(0, 25).forEach((e) => console.log("  " + e));
    if (liveErrors.length > 25) console.log(`  …and ${liveErrors.length - 25} more`);
  }
  if (acknowledged.length) {
    console.log(`\n${acknowledged.length} known and blocked (not resolved — see PROGRESS.md):`);
    acknowledged.forEach((a) => console.log(`  ${a.text}\n      gate: ${a.gate}`));
  }
  if (warnings.length) console.log(`\n${warnings.length} warning(s) — see PROGRESS.md`);
}
console.log(`\n${liveErrors.length ? "FAIL" : "OK"}  —  PROGRESS.md written`);

if (CHECK && liveErrors.length) process.exit(1);
